name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: sudo apt-get -y install libpcap-dev
    - name: bootstrap
      run: sh bootstrap
    - name: configure
      run: ./configure --enable-sflow --enable-maxmind --enable-tor --enable-nfpcapd
    - name: make
      run: make
    - name: make check
      run: make check
